// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: zethchain/mining/v1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2442ba9bfac8201a, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2442ba9bfac8201a, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

// QueryMiningHistoryRequest is request type for the Query/MiningHistory RPC method.
type QueryMiningHistoryRequest struct {
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
}

func (m *QueryMiningHistoryRequest) Reset()         { *m = QueryMiningHistoryRequest{} }
func (m *QueryMiningHistoryRequest) String() string { return proto.CompactTextString(m) }
func (*QueryMiningHistoryRequest) ProtoMessage()    {}
func (*QueryMiningHistoryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2442ba9bfac8201a, []int{2}
}
func (m *QueryMiningHistoryRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryMiningHistoryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryMiningHistoryRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryMiningHistoryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryMiningHistoryRequest.Merge(m, src)
}
func (m *QueryMiningHistoryRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryMiningHistoryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryMiningHistoryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryMiningHistoryRequest proto.InternalMessageInfo

func (m *QueryMiningHistoryRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

// QueryMiningHistoryResponse is response type for the Query/MiningHistory RPC method.
type QueryMiningHistoryResponse struct {
	LastMineTime string `protobuf:"bytes,1,opt,name=last_mine_time,json=lastMineTime,proto3" json:"last_mine_time,omitempty"`
	TotalMined   string `protobuf:"bytes,2,opt,name=total_mined,json=totalMined,proto3" json:"total_mined,omitempty"`
	MineCount    string `protobuf:"bytes,3,opt,name=mine_count,json=mineCount,proto3" json:"mine_count,omitempty"`
}

func (m *QueryMiningHistoryResponse) Reset()         { *m = QueryMiningHistoryResponse{} }
func (m *QueryMiningHistoryResponse) String() string { return proto.CompactTextString(m) }
func (*QueryMiningHistoryResponse) ProtoMessage()    {}
func (*QueryMiningHistoryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2442ba9bfac8201a, []int{3}
}
func (m *QueryMiningHistoryResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryMiningHistoryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryMiningHistoryResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryMiningHistoryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryMiningHistoryResponse.Merge(m, src)
}
func (m *QueryMiningHistoryResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryMiningHistoryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryMiningHistoryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryMiningHistoryResponse proto.InternalMessageInfo

func (m *QueryMiningHistoryResponse) GetLastMineTime() string {
	if m != nil {
		return m.LastMineTime
	}
	return ""
}

func (m *QueryMiningHistoryResponse) GetTotalMined() string {
	if m != nil {
		return m.TotalMined
	}
	return ""
}

func (m *QueryMiningHistoryResponse) GetMineCount() string {
	if m != nil {
		return m.MineCount
	}
	return ""
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "zethchain.mining.v1.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "zethchain.mining.v1.QueryParamsResponse")
	proto.RegisterType((*QueryMiningHistoryRequest)(nil), "zethchain.mining.v1.QueryMiningHistoryRequest")
	proto.RegisterType((*QueryMiningHistoryResponse)(nil), "zethchain.mining.v1.QueryMiningHistoryResponse")
}

func init() { proto.RegisterFile("zethchain/mining/v1/query.proto", fileDescriptor_2442ba9bfac8201a) }

var fileDescriptor_2442ba9bfac8201a = []byte{
	// 446 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0x41, 0xeb, 0xd3, 0x30,
	0x18, 0xc6, 0x9b, 0x89, 0x93, 0xe5, 0xaf, 0x82, 0xf9, 0xef, 0x50, 0x3b, 0xd7, 0x8d, 0x4e, 0x71,
	0x4c, 0x68, 0xe8, 0xc4, 0xab, 0x87, 0x79, 0xf1, 0x32, 0xd0, 0xa1, 0x17, 0x2f, 0x23, 0x5b, 0x43,
	0x17, 0x58, 0x93, 0xae, 0xc9, 0x86, 0xf3, 0x24, 0xfb, 0x04, 0x82, 0x67, 0xef, 0xe2, 0xc9, 0x8f,
	0xb1, 0xe3, 0xc0, 0x8b, 0x27, 0x91, 0x4d, 0xf0, 0x6b, 0x48, 0x93, 0x4c, 0x19, 0x76, 0xe8, 0xa5,
	0xa4, 0x4f, 0x7e, 0xcf, 0xfb, 0x3e, 0xef, 0xdb, 0xc2, 0xd6, 0x1b, 0xaa, 0x66, 0xd3, 0x19, 0x61,
	0x1c, 0xa7, 0x8c, 0x33, 0x9e, 0xe0, 0x55, 0x84, 0x17, 0x4b, 0x9a, 0xaf, 0xc3, 0x2c, 0x17, 0x4a,
	0xa0, 0xcb, 0xdf, 0x40, 0x68, 0x80, 0x70, 0x15, 0x79, 0xb7, 0x48, 0xca, 0xb8, 0xc0, 0xfa, 0x69,
	0x38, 0xaf, 0x37, 0x15, 0x32, 0x15, 0x12, 0x4f, 0x88, 0xa4, 0xa6, 0x00, 0x5e, 0x45, 0x13, 0xaa,
	0x48, 0x84, 0x33, 0x92, 0x30, 0x4e, 0x14, 0x13, 0xdc, 0xb2, 0xf5, 0x44, 0x24, 0x42, 0x1f, 0x71,
	0x71, 0xb2, 0xea, 0x9d, 0x44, 0x88, 0x64, 0x4e, 0x31, 0xc9, 0x18, 0x26, 0x9c, 0x0b, 0xa5, 0x2d,
	0xd2, 0xde, 0xb6, 0xcb, 0x82, 0x66, 0x24, 0x27, 0xa9, 0x25, 0x82, 0x3a, 0x44, 0xcf, 0x8b, 0xbe,
	0xcf, 0xb4, 0x38, 0xa2, 0x8b, 0x25, 0x95, 0x2a, 0x78, 0x09, 0x2f, 0x4f, 0x54, 0x99, 0x09, 0x2e,
	0x29, 0x7a, 0x0c, 0xab, 0xc6, 0xec, 0x82, 0x36, 0xe8, 0x5e, 0xf4, 0x1b, 0x61, 0xc9, 0x9c, 0xa1,
	0x31, 0x0d, 0x6a, 0xdb, 0x6f, 0x2d, 0xe7, 0xe3, 0xcf, 0xcf, 0x3d, 0x30, 0xb2, 0xae, 0xe0, 0x11,
	0xbc, 0xad, 0xcb, 0x0e, 0x35, 0xfb, 0x94, 0x49, 0x25, 0xf2, 0xb5, 0xed, 0x89, 0x5c, 0x78, 0x8d,
	0xc4, 0x71, 0x4e, 0xa5, 0xa9, 0x5e, 0x1b, 0x1d, 0x5f, 0x83, 0x0d, 0x80, 0x5e, 0x99, 0xcf, 0xa6,
	0xba, 0x0b, 0x6f, 0xce, 0x89, 0x54, 0xe3, 0x94, 0x71, 0x3a, 0x56, 0x2c, 0xa5, 0xd6, 0x7f, 0xbd,
	0x50, 0x87, 0x8c, 0xd3, 0x17, 0x2c, 0xa5, 0xa8, 0x05, 0x2f, 0x94, 0x50, 0x64, 0xae, 0xb1, 0xd8,
	0xad, 0x68, 0x04, 0x6a, 0xa9, 0x60, 0x62, 0xd4, 0x84, 0x50, 0x57, 0x98, 0x8a, 0x25, 0x57, 0xee,
	0x15, 0x7d, 0x5f, 0x2b, 0x94, 0x27, 0x85, 0xd0, 0xff, 0x54, 0x81, 0x57, 0x75, 0x08, 0xf4, 0x16,
	0xc0, 0xaa, 0x99, 0x11, 0xdd, 0x2f, 0x5d, 0xc0, 0xdf, 0x0b, 0xf5, 0xba, 0xff, 0x06, 0xcd, 0x34,
	0x41, 0x67, 0xf3, 0xe5, 0xc7, 0xfb, 0x4a, 0x13, 0x35, 0xf0, 0xf9, 0x6f, 0x87, 0x3e, 0x00, 0x78,
	0xe3, 0x64, 0x19, 0x28, 0x3c, 0xdf, 0xa0, 0x6c, 0xdb, 0x1e, 0xfe, 0x6f, 0xde, 0xe6, 0x7a, 0xa0,
	0x73, 0xdd, 0x43, 0x9d, 0xd2, 0x5c, 0xe6, 0x34, 0x9e, 0x19, 0xd3, 0xa0, 0xbf, 0xdd, 0xfb, 0x60,
	0xb7, 0xf7, 0xc1, 0xf7, 0xbd, 0x0f, 0xde, 0x1d, 0x7c, 0x67, 0x77, 0xf0, 0x9d, 0xaf, 0x07, 0xdf,
	0x79, 0xe5, 0xfe, 0x71, 0xbf, 0x3e, 0xfa, 0xd5, 0x3a, 0xa3, 0x72, 0x52, 0xd5, 0x3f, 0xe4, 0xc3,
	0x5f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x90, 0xa2, 0xcb, 0x6a, 0x5d, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// MiningHistory queries the mining history of a specific address.
	MiningHistory(ctx context.Context, in *QueryMiningHistoryRequest, opts ...grpc.CallOption) (*QueryMiningHistoryResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/zethchain.mining.v1.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) MiningHistory(ctx context.Context, in *QueryMiningHistoryRequest, opts ...grpc.CallOption) (*QueryMiningHistoryResponse, error) {
	out := new(QueryMiningHistoryResponse)
	err := c.cc.Invoke(ctx, "/zethchain.mining.v1.Query/MiningHistory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// MiningHistory queries the mining history of a specific address.
	MiningHistory(context.Context, *QueryMiningHistoryRequest) (*QueryMiningHistoryResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) MiningHistory(ctx context.Context, req *QueryMiningHistoryRequest) (*QueryMiningHistoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MiningHistory not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/zethchain.mining.v1.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_MiningHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryMiningHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).MiningHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/zethchain.mining.v1.Query/MiningHistory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).MiningHistory(ctx, req.(*QueryMiningHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var Query_serviceDesc = _Query_serviceDesc
var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "zethchain.mining.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "MiningHistory",
			Handler:    _Query_MiningHistory_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "zethchain/mining/v1/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryMiningHistoryRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryMiningHistoryRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryMiningHistoryRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryMiningHistoryResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryMiningHistoryResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryMiningHistoryResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.MineCount) > 0 {
		i -= len(m.MineCount)
		copy(dAtA[i:], m.MineCount)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.MineCount)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.TotalMined) > 0 {
		i -= len(m.TotalMined)
		copy(dAtA[i:], m.TotalMined)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.TotalMined)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.LastMineTime) > 0 {
		i -= len(m.LastMineTime)
		copy(dAtA[i:], m.LastMineTime)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.LastMineTime)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryMiningHistoryRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryMiningHistoryResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.LastMineTime)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.TotalMined)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.MineCount)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryMiningHistoryRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryMiningHistoryRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryMiningHistoryRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryMiningHistoryResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryMiningHistoryResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryMiningHistoryResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastMineTime", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LastMineTime = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalMined", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TotalMined = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MineCount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MineCount = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
